[package]
name = "jpeg-decoder"
version = "0.1.10"
authors = ["Ulf Nilsson <kaksmet@gmail.com>"]
description = "JPEG decoder"
repository = "https://github.com/kaksmet/jpeg-decoder"
readme = "README.md"
keywords = ["JPEG", "decoder", "image"]
license = "MIT / Apache-2.0"

exclude = ["tests/*"]

[dependencies]
byteorder = "1.0"

[dependencies.rayon]
version = "0.6"
optional = true

[features]
default = ["rayon"]

[dev-dependencies]
docopt = "0.7"
walkdir = "1.0"
png = "0.5"
